In [1]:
import numpy as np

In [3]:
arr =  np.asarray([[0,2,4], [4,5,1], [8,3,5]])

In [4]:
arr

array([[0, 2, 4],
       [4, 5, 1],
       [8, 3, 5]])

In [5]:
arr[0][1]

2

In [6]:
arr[1][2
      ]

1

In [8]:
arr[2]

array([8, 3, 5])

In [9]:
arr[1,1]

5

In [10]:
arr[:2,:2]

array([[0, 2],
       [4, 5]])

In [11]:
arr[1:,:]


array([[4, 5, 1],
       [8, 3, 5]])