In [1]:
import numpy as np

In [3]:
arr =  np.asarray([[0,2,4], [4,5,1], [8,3,5]])

In [4]:
arr

array([[0, 2, 4],
       [4, 5, 1],
       [8, 3, 5]])

In [5]:
arr[0][1]

2

In [6]:
arr[1][2
      ]

1

In [8]:
arr[2]

array([8, 3, 5])

In [9]:
arr[1,1]

5

In [10]:
arr[:2,:2]

array([[0, 2],
       [4, 5]])

In [11]:
arr[1:,:]


array([[4, 5, 1],
       [8, 3, 5]])

In [12]:
arr.shape

(3, 3)

In [13]:
arr.max()

8

In [14]:
arr.argmax()

6

In [15]:
new_arr =  np.arange(12)

In [16]:
bool_=new_arr > 4

In [17]:
bool_


array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True])

In [18]:
new_arr[bool_]

array([ 5,  6,  7,  8,  9, 10, 11])

In [19]:
new_arr[new_arr > 1]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [20]:
prac_arr =  np.arange(50).reshape(5,10)

In [21]:
prac_arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [23]:
prac_arr[3:,5:]

array([[35, 36, 37, 38, 39],
       [45, 46, 47, 48, 49]])