In [1]:
import numpy as np

In [2]:
arr =  np.arange(0,16)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [4]:
np.arange(0, 16, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [5]:
np.linspace(0,16,2)

array([ 0., 16.])

In [6]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [7]:
arr//arr

/tmp/ipykernel_12188/3990451985.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  arr//arr


array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [8]:
arr/arr

/tmp/ipykernel_12188/1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.])

In [9]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [10]:
arr ** arr

array([                 1,                  1,                  4,
                       27,                256,               3125,
                    46656,             823543,           16777216,
                387420489,        10000000000,       285311670611,
            8916100448256,    302875106592253,  11112006825558016,
       437893890380859375])

In [11]:
np.max(arr)

15

In [12]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [13]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784])

In [14]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06])

In [15]:
np.log(arr)

/tmp/ipykernel_12188/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 ])