In [1]:
import numpy as np

In [2]:
arr =  np.array([1,2,3])

In [3]:
arr

array([1, 2, 3])

### **Casting python arrays to numpy arrays**

In [5]:
np.array([[1,2,3],[456]], dtype=object) #numpy two dimensional arrays

array([list([1, 2, 3]), list([456])], dtype=object)

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.zeros(2)

array([0., 0.])

In [13]:
np.zeros((2,5))#array of zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.linspace(0,2,4)
# linear space of 4 points from zero to 2

array([0.        , 0.66666667, 1.33333333, 2.        ])

In [19]:
np.eye(2) #identity matrix

array([[1., 0.],
       [0., 1.]])

In [26]:
randarr =  np.random.randint(0,5)

In [27]:
randarr

1

In [29]:
ranarr =  np.random.randint(0,5,3) # k=3

In [31]:
ranarr

array([1, 3, 0])

In [33]:
rarr =  np.random.randn(4)

In [35]:
rarr

array([-0.55798788,  0.30762832, -1.674131  , -0.20409378])

In [45]:
anarr =  np.random.randint(0,20,16)

In [46]:
anarr

array([ 0, 13, 18,  7, 12,  7,  8, 19, 13,  5, 12,  0,  7, 15,  0,  6])

In [47]:
anarr.shape

(16,)

In [55]:
anarr.reshape(4,4)

array([[ 0, 13, 18,  7],
       [12,  7,  8, 19],
       [13,  5, 12,  0],
       [ 7, 15,  0,  6]])

In [56]:
anarr.shape

(16,)

In [58]:
x =  np.eye(3)

In [59]:
x.shape

(3, 3)

In [60]:
v =  anarr.reshape(4,4)

In [61]:
v.shape

(4, 4)

In [62]:
v.max()

19

In [63]:
v.argmax()

7

In [64]:
np.asarray([1,2,3,4])

array([1, 2, 3, 4])

In [65]:
np.asarray([[1,2], [2,3]])

array([[1, 2],
       [2, 3]])

In [66]:
np.asarray([1,2,3,4], dtype=np.int32
          )

array([1, 2, 3, 4], dtype=int32)

In [2]:
import numpy as np

In [3]:
np.asarray([1,2,3])

array([1, 2, 3])

In [4]:
np.eye(3
      )

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
arr =  np.arange(0, 100)

In [6]:
arr[1:10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr[0:9] =  5

In [9]:
arr

array([ 5,  5,  5,  5,  5,  5,  5,  5,  5,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [10]:
uexe = arr.copy()


In [11]:
uexe

array([ 5,  5,  5,  5,  5,  5,  5,  5,  5,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])